### ISSUE TITLE
Better connection method like token.

### ISSUE THREAD

**Issue by eax64** [vigilate/backend#104]
Instead of using a basic auth, we should use a token or something that will be savec in the cookie.

**Comment by ampotos** [comment]
What we need is to have session for the frontend. To use django session we have to change a lot of thing because actually our user is not registered as django user, and we don"t use the function "login" after authentication (which is suppose to start the session).
We also need a token auth of reseller (a check to allaow that only for user with are reseller and add the token connection in our authentication).
We may also need a specific authentication class available only for the uprog view to allow the scanner to authenticate only on that view.

**Comment by ampotos** [comment]
create token sur un create de table token
table : main id : token, date creation (life time : 1day), associated user.
create : as a loggin (just crate the token and send it back).
get: token exist or not.
delete: use when logout.

in authenticator:
token is in header var: AUTHORIZATION
check if token exit;, if not send a 403. (exception for auth token).
when token exist check if expired or not (if yes delete + return 403).
