### ISSUE TITLE
check alerte on program update only if version is update

### ISSUE THREAD

**Issue by ampotos** [vigilate/backend#149]

**Comment by ampotos** [comment]
Also recheck when name is changed

**Comment by fr0gRIP** [comment]
We use the name provided by the user to get the existing program, so we are actually not able to modify the name of a program.

**Comment by eax64** [comment]
This issue was more about the update of an unique program via sending a PATCH  to  /upgrog/id/. That will call the `update()` and `perform_update()` function. (and not a POST to /uprog/)

We are already doing the check when the name is changed because we actually call the `alerts.check_prog()` for any change on any field cf: https://github.com/vigilate/backend/blob/master/vigilate_backend/views.py#L199

The problem is that we also do the check when we change the alert type/alert score, and we shouldn't.

So the code that you have added have to be moved to the `perform_update()` instead. (And shouldn't stay on the `create()` because we always only modify the version here so there is no need for this code here)
This code should call the `alerts.check_prog()` only for an update on prog_name or prog_version.
