### ISSUE TITLE
Check that the user_id sent in post/patch/put/delete requests is the user_id of the current user

### ISSUE THREAD

**Issue by eax64** [vigilate/backend#61]
Currently, an user can do action on behalf of other user by using another user_id in there requests.

**Comment by fr0gRIP** [comment]
I will explain the "strange" method that I used

I firstly wanted to check the user id in the middleware, but problem : in the middleware, the current user stored in **request.user** is an AnonymousUser instance, even if I try to get the user in an overrided version of **process_view()**

In fact, the user is considered authenticated when we are in the view, but not in the middleware, so I did'nt find any way to get the current user in the middleware.

However, the custom authentication method is called for each request on the API, that's why I decided to add a check of the data in this method (to verify if the current user id correspond to the user he's trying to modify).

It's a lil bit crap imho, but as I said, it's actually the only solution I found for that problem, and I think it's not worst than add a check in each viewset.

If anybody have a better solution... go , I'm a little frustrated not to have found a cleaner solution.

**Comment by eax64** [comment]
Indeed, the middleware is called before the auth, and at that point it's an anonymousUser. So you can't do that in the middleware.

As you said, you could do that by adding a method in each view (as in http://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#associating-snippets-with-users) but that would be a lot of code duplication.

So I think that what you did is a good solution.

However, 2 little details:
Some model use user_id and not user. (unifying the model could be a good idea)
You should probably check if the value that you put into int() is a valid int to avoid a valueerror. For that you could check with str.is_digit() or is_numeric(), I don't know whitch one is fitting the best.

**Comment by fr0gRIP** [comment]
UserProgam model was containg a "user_id" field, now updated to be "user" (in a previous commit)

Concerning the value sent to by POST PUT PATCH DELETE requests, a condition is added to check if the value is an instance of int and if it's above 0 . else the request will return an error.

**Comment by eax64** [comment]
It is working, the travis error that you are seing is because of https://github.com/vigilate/module_com_bdd/issues/1#issuecomment-230074861

But isinstance is maybe not what you want.
You are checking if `value` is an int object, and then you convert it to int with int(). This is useless since it is already an int at that point.

The `value.isdigit()` would be more logic.
Also checking for `value` to be greater than 0 is probably not usefull easier as it is already "handled" by the equality with the current user id.

**Comment by fr0gRIP** [comment]
Indeed, I should modify the int conversion in the condition, however, the value sent in the json is supposed to be an int, (the waited user value is the id of an user (in all cases imho) , so always an integer, no ? ). if the value is sent as string, the request will fail anyway in the view . So I think isnumeric /isdigit is not the good solution to solve the problem because we wait for an integer, which has no isdigit of isnumeric method . am I wrong ? :)

**Comment by eax64** [comment]
Ok then.
No isdigit and no int() either, and that sould be ok.
