### ISSUE TITLE
create station when add prog if it doesn't exist

### ISSUE THREAD

**Issue by ampotos** [vigilate/backend#68]
when a program is add, the specified station has to be created if it doesn't exist

**Comment by ampotos** [comment]
when a program is add from the front-end the poste the poste can be a string.

**Comment by fr0gRIP** [comment]
Need more informations, am I just suppposed to set a default poste name when the program is created ?

**Comment by eax64** [comment]
When creating a program, the user have to choose the station (field called `poste`) where this program is installed.

Currently, the station (`poste`) value in the UserProgram model is a simple int.
Instead, it should be a foreignkey of the Station model so the two things are linked together.

From the frontend, the user should be able to put the name of the station instead of a number.
If this name do not exists (in the Station model), then, we should create this station.

So there is two things here:
#### Backend point of view
* The `poste` field is change to a ForeignKey of Station

#### Frontend point of view 
* The user should be able to easily choose the station or create one without having to change menu
  * A nice way of doing this from the user point of view would be to have a dropdown box with the list of station, and a "new station" or something on the list so the user could add a station while adding the program


I think that most of what this issue describe is actually more frontend related than backend related.

We can already add a station by a POST request.
We are already sending an information about the station from the frontend when adding a program (the IntValue that will have to be changed to a ForeignKey).

Changing the backend so it could handle a string instead of the ID and creating station if this string is not linked to a station is probably not the best thing to do and wouldn't be trivial to do correctly. 

#### Conclusion / TL;DR
I personaly think that we should actualy keep it simple on the backend side by just receiving the ID corresponding to the right station.
So the only change would be to modify the IntValue of the UserProgram in a ForeignKey.
